### ISSUE TITLE
Can I have the pre-training code for LayoutLM2?

### ISSUE THREAD

**Issue by runorz** [microsoft/unilm#307] opened 2021-03-08 03:43 UTC
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): LayoutLM
Hi. Thanks for your great work on LayoutLMv2.

I am trying to do some experiment on LayoutLMv2 especially in the pre-trainning stage, so I wonder if it is possible to have the pre-training code?

**Comment by wolfshow** [comment] 2021-04-01 07:28
Duplicate of #279

**Closed by wolfshow** 2021-04-01 07:28 UTC
