### ISSUE TITLE
LayoutLM V2 model problem

### ISSUE THREAD

**Issue by paulpaul91** [microsoft/unilm#300] opened 2021-02-25 07:49 UTC
**Describe**
Model I am using LayoutLM V2:
1.In TIM, 15% images are replaced and 5% are dropped. what is the meanings of droped? how to do it?
2.In TIA, the cover negative samples are the all uncover chars? the positive 、negative samples varies too much.
3.Is the scale of image and text uniform？

**Comment by wolfshow** [comment] 2021-04-01 07:29
Duplicate of #279

**Closed by wolfshow** 2021-04-01 07:29 UTC
